server:
  port: 8080
  servlet:
    context-path: /root

spring:
  datasource:
    name: test
    #    url: jdbc:mysql://10.5.17.34:3306/rbac_db?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    url: jdbc:mysql://127.0.0.1:3306/rbac_db?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    #    password: root
    # druid 连接池
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  type-aliases-package:
    com.trs.gx
  mapper-locations:
    classpath:mapping/*.xml
  #  开启驼峰下划线自动转化
  configuration:
    map-underscore-to-camel-case: true